import Head from 'next/head';
import { Card, Grid, Loading } from '@nextui-org/react';
import { NavBar } from '../components/Navbar';
import { useGetGalleryMedia } from './hooks/api/gallery';

export default function Home() {
  const { isLoading, data: galleryQueryData } = useGetGalleryMedia();

  if (isLoading) {
    return (
      <Loading
        css={{
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          height: '100%',
        }}
        size="xl"
        type="gradient"
      >
        Loading
      </Loading>
    );
  }

  return (
    <div>
      <Head>
        <title>Makeup By J&apos;Victoria</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/favicon.ico" />
      </Head>
      <header>
        <NavBar />
      </header>

      <main>
        <h1>Gallery</h1>
        <Grid.Container gap={2} justify="center">
          {galleryQueryData?.map((media) => {
            const containsVideo = media.mediaType.includes('video');
            if (!containsVideo) {
              return (
                <Grid key={media.id}>
                  <Card css={{ height: '100%' }} isHoverable isPressable>
                    <Card.Body css={{ p: 0 }}>
                      <Card.Image
                        css={{ height: '100%' }}
                        objectFit="fill"
                        width={200}
                        height={200}
                        src={media.mediaName}
                        alt=""
                      />
                    </Card.Body>
                  </Card>
                </Grid>
              );
            }
            return (
              <Grid key={media.id}>
                <Card css={{ height: '100%' }} isHoverable isPressable>
                  <Card.Body css={{ p: 0 }}>
                    <Card.Image
                      css={{ height: '100%' }}
                      objectFit="fill"
                      width={200}
                      height={200}
                      src={media.mediaName}
                      alt=""
                    />
                  </Card.Body>
                </Card>
              </Grid>
            );
          })}
        </Grid.Container>
      </main>
    </div>
  );
}
